project_id = "jyhxcqlsinxodfcdrlgx"

[functions.contrato-publico]
verify_jwt = false

[functions.assinar-contrato]
verify_jwt = false

[functions.extrair-frame-video]
verify_jwt = false

[functions.meta-lead-webhook]
verify_jwt = false
